'use client'

import { loadCrudLookupOptions } from '@/src/components/crud-base/crud-client'
import type { CrudModuleConfig, CrudRecord } from '@/src/components/crud-base/types'
import { StatusBadge } from '@/src/components/ui/status-badge'
import { formatApiDateToInput, formatInputDateToApiEnd, formatInputDateToApiStart } from '@/src/lib/date-input'
import { toLookupOption } from '@/src/lib/lookup-options'
import { parseInteger } from '@/src/lib/value-parsers'
import { formatPriceStockDecimal, parsePriceStockDecimal, PRODUCT_BRANCH_STATUS_META } from '@/src/features/precos-estoques/services/precos-estoques-shared'

export const PRODUTOS_FILIAIS_CONFIG: CrudModuleConfig = {
  key: 'produtos-filiais',
  resource: 'produtos/filiais',
  routeBase: '/produtos-x-filiais',
  featureKey: 'produtosFiliais',
  listTitleKey: 'priceStock.productBranches.title',
  listTitle: 'Produtos x Filiais',
  listDescriptionKey: 'priceStock.productBranches.listDescription',
  listDescription: 'Listagem com produto, filial, tabela de preço e status.',
  formTitleKey: 'priceStock.productBranches.formTitle',
  formTitle: 'Produto x Filial',
  breadcrumbSectionKey: 'routes.precosEstoques',
  breadcrumbSection: 'Preços e Estoques',
  breadcrumbModuleKey: 'routes.produtosFiliais',
  breadcrumbModule: 'Produtos x Filiais',
  listEmbed: 'produto,filial,tabela_preco,canal_distribuicao',
  formEmbed: 'produto,filial,tabela_preco,canal_distribuicao',
  defaultFilters: {
    page: 1,
    perPage: 15,
    orderBy: 'id_produto',
    sort: 'desc',
    id_produto: '',
    id_filial: '',
    id_tabela_preco: '',
    ativo: '',
    status: '',
  },
  columns: [
    {
      id: 'id_produto',
      labelKey: 'priceStock.productBranches.fields.product',
      label: 'Produto',
      sortKey: 'id_produto',
      tdClassName: 'font-semibold text-slate-950',
      render: (record) => String((record.produto as { nome?: unknown } | null)?.nome || record.id_produto || '-'),
      filter: {
        kind: 'lookup',
        key: 'id_produto',
        loadOptions: (query, page, perPage) => loadCrudLookupOptions('produtos', query, page, perPage).then((items) => items.map((item) => ({ id: item.value, label: item.label }))),
      },
    },
    {
      id: 'id_filial',
      labelKey: 'priceStock.productBranches.fields.branch',
      label: 'Filial',
      sortKey: 'id_filial',
      render: (record) => String((record.filial as { nome_fantasia?: unknown; nome?: unknown } | null)?.nome_fantasia || (record.filial as { nome?: unknown } | null)?.nome || record.id_filial || '-'),
      filter: {
        kind: 'lookup',
        key: 'id_filial',
        loadOptions: (query, page, perPage) => loadCrudLookupOptions('filiais', query, page, perPage).then((items) => items.map((item) => ({ id: item.value, label: item.label }))),
      },
    },
    {
      id: 'id_tabela_preco',
      labelKey: 'priceStock.productBranches.fields.priceTable',
      label: 'Tabela de preço',
      sortKey: 'id_tabela_preco',
      render: (record) => String((record.tabela_preco as { nome?: unknown } | null)?.nome || '-'),
      filter: {
        kind: 'lookup',
        key: 'id_tabela_preco',
        loadOptions: (query, page, perPage) => loadCrudLookupOptions('tabelas_preco', query, page, perPage).then((items) => items.map((item) => ({ id: item.value, label: item.label }))),
      },
    },
    {
      id: 'status',
      labelKey: 'priceStock.productBranches.fields.status',
      label: 'Status',
      sortKey: 'status',
      render: (record) => {
        const meta = PRODUCT_BRANCH_STATUS_META[String(record.status || '') as keyof typeof PRODUCT_BRANCH_STATUS_META]
        return <StatusBadge tone={meta?.tone ?? 'neutral'}>{meta?.label ?? String(record.status || '-')}</StatusBadge>
      },
      filter: {
        kind: 'select',
        key: 'status',
        options: [
          { value: 'disponivel', label: 'Disponível' },
          { value: 'indisponivel', label: 'Indisponível' },
          { value: 'em_revisao', label: 'Em revisão' },
          { value: 'fora_de_linha', label: 'Fora de linha' },
        ],
      },
    },
    { id: 'ativo', labelKey: 'simpleCrud.fields.active', label: 'Ativo', sortKey: 'ativo', thClassName: 'w-[100px]', valueKey: 'ativo', filter: { kind: 'select', key: 'ativo', options: [{ value: '1', label: 'Sim' }, { value: '0', label: 'Não' }] } },
  ],
  mobileTitle: (record) => String((record.produto as { nome?: unknown } | null)?.nome || '-'),
  mobileSubtitle: (record) => String((record.filial as { nome_fantasia?: unknown } | null)?.nome_fantasia || record.id_filial || '-'),
  mobileMeta: (record) => PRODUCT_BRANCH_STATUS_META[String(record.status || '') as keyof typeof PRODUCT_BRANCH_STATUS_META]?.label || String(record.status || '-'),
  sections: [
    {
      id: 'general',
      titleKey: 'priceStock.sections.general',
      title: 'Dados gerais',
      layout: 'rows',
      fields: [
        { key: 'ativo', labelKey: 'simpleCrud.fields.active', label: 'Ativo', type: 'toggle' },
        { key: 'promocao_ecommerce', labelKey: 'priceStock.productBranches.fields.ecommercePromotion', label: 'Promoção e-commerce', type: 'toggle' },
        { key: 'estoque_positivo', labelKey: 'priceStock.productBranches.fields.positiveStock', label: 'Estoque positivo', type: 'toggle' },
        { key: 'id_produto', labelKey: 'priceStock.productBranches.fields.product', label: 'Produto', type: 'lookup', optionsResource: 'produtos', lookupStateKey: 'id_produto_lookup', required: true, disabled: ({ isEditing }) => isEditing },
        { key: 'id_filial', labelKey: 'priceStock.productBranches.fields.branch', label: 'Filial', type: 'lookup', optionsResource: 'filiais', lookupStateKey: 'id_filial_lookup', required: true, disabled: ({ isEditing }) => isEditing },
        { key: 'id_tabela_preco', labelKey: 'priceStock.productBranches.fields.priceTable', label: 'Tabela de preço', type: 'lookup', optionsResource: 'tabelas_preco', lookupStateKey: 'id_tabela_preco_lookup', disabled: ({ isEditing }) => isEditing },
        { key: 'id_canal_distribuicao_cliente', labelKey: 'priceStock.productBranches.fields.distributionChannel', label: 'Canal de distribuição', type: 'lookup', optionsResource: 'canais_distribuicao', lookupStateKey: 'id_canal_distribuicao_lookup', disabled: ({ isEditing }) => isEditing },
        {
          key: 'status',
          labelKey: 'priceStock.productBranches.fields.status',
          label: 'Status',
          type: 'select',
          required: true,
          options: [
            { value: 'disponivel', labelKey: 'priceStock.productBranches.options.available', label: 'Disponível' },
            { value: 'indisponivel', labelKey: 'priceStock.productBranches.options.unavailable', label: 'Indisponível' },
            { value: 'em_revisao', labelKey: 'priceStock.productBranches.options.inReview', label: 'Em revisão' },
            { value: 'fora_de_linha', labelKey: 'priceStock.productBranches.options.discontinued', label: 'Fora de linha' },
          ],
        },
        {
          key: 'tipo_preco',
          labelKey: 'priceStock.productBranches.fields.priceType',
          label: 'Tipo de preço',
          type: 'select',
          options: [
            { value: '', labelKey: 'common.select', label: 'Selecione' },
            { value: 'normal', labelKey: 'priceStock.productBranches.options.normalPrice', label: 'Normal' },
            { value: 'm2', labelKey: 'priceStock.productBranches.options.squareMeter', label: 'm²' },
            { value: 'm3', labelKey: 'priceStock.productBranches.options.cubicMeter', label: 'm³' },
          ],
        },
        { key: 'prazo_entrega', labelKey: 'priceStock.productBranches.fields.deliveryLeadTime', label: 'Prazo de entrega', type: 'number' },
      ],
    },
    {
      id: 'stock',
      titleKey: 'priceStock.productBranches.sections.stock',
      title: 'Estoques e limites',
      layout: 'rows',
      fields: [
        { key: 'estoque_minimo', labelKey: 'priceStock.productBranches.fields.minimumStock', label: 'Estoque mínimo', type: 'number' },
        { key: 'estoque_disponivel', labelKey: 'priceStock.productBranches.fields.availableStock', label: 'Estoque disponível', type: 'number' },
        { key: 'estoque_reservado', labelKey: 'priceStock.productBranches.fields.reservedStock', label: 'Estoque reservado', type: 'number' },
        { key: 'pedido_minimo', labelKey: 'priceStock.productBranches.fields.minimumOrder', label: 'Pedido mínimo', type: 'text', mask: 'currency', prefixText: 'R$' },
        { key: 'pedido_maximo', labelKey: 'priceStock.productBranches.fields.maximumOrder', label: 'Pedido máximo', type: 'text', mask: 'currency', prefixText: 'R$' },
      ],
    },
    {
      id: 'pricing',
      titleKey: 'priceStock.productBranches.sections.pricing',
      title: 'Preços',
      layout: 'rows',
      fields: [
        { key: 'preco', labelKey: 'priceStock.productBranches.fields.price', label: 'Preço', type: 'text', mask: 'currency', prefixText: 'R$' },
        { key: 'preco_promocao', labelKey: 'priceStock.productBranches.fields.promotionPrice', label: 'Preço promocional', type: 'text', mask: 'currency', prefixText: 'R$' },
        { key: 'preco_custo', labelKey: 'priceStock.productBranches.fields.costPrice', label: 'Preço de custo', type: 'text', mask: 'currency', prefixText: 'R$' },
        { key: 'preco_fidelidade', labelKey: 'priceStock.productBranches.fields.loyaltyPrice', label: 'Preço fidelidade', type: 'text', mask: 'currency', prefixText: 'R$' },
        { key: 'preco_app', labelKey: 'priceStock.productBranches.fields.appPrice', label: 'Preço APP', type: 'text', mask: 'currency', prefixText: 'R$' },
        { key: 'preco_minimo', labelKey: 'priceStock.productBranches.fields.minimumPrice', label: 'Preço mínimo', type: 'text', mask: 'currency', prefixText: 'R$' },
        { key: 'preco_venda', labelKey: 'priceStock.productBranches.fields.salePrice', label: 'Preço de venda', type: 'text', mask: 'currency', prefixText: 'R$' },
        { key: 'desconto', labelKey: 'priceStock.productBranches.fields.discount', label: 'Desconto', type: 'text', mask: 'decimal', suffixText: '%' },
        { key: 'acrescimo', labelKey: 'priceStock.productBranches.fields.increase', label: 'Acréscimo', type: 'text', mask: 'decimal', suffixText: '%' },
      ],
    },
    {
      id: 'dates',
      titleKey: 'priceStock.productBranches.sections.dates',
      title: 'Vigências',
      layout: 'rows',
      fields: [
        { key: 'data_inicio_promocao', labelKey: 'priceStock.productBranches.fields.promotionStartDate', label: 'Início promoção', type: 'date' },
        { key: 'data_fim_promocao', labelKey: 'priceStock.productBranches.fields.promotionEndDate', label: 'Fim promoção', type: 'date' },
        { key: 'data_inicio_fidelidade', labelKey: 'priceStock.productBranches.fields.loyaltyStartDate', label: 'Início fidelidade', type: 'date' },
        { key: 'data_fim_fidelidade', labelKey: 'priceStock.productBranches.fields.loyaltyEndDate', label: 'Fim fidelidade', type: 'date' },
        { key: 'data_inicio_app', labelKey: 'priceStock.productBranches.fields.appStartDate', label: 'Início APP', type: 'date' },
        { key: 'data_fim_app', labelKey: 'priceStock.productBranches.fields.appEndDate', label: 'Fim APP', type: 'date' },
        { key: 'data_validade', labelKey: 'priceStock.productBranches.fields.expirationDate', label: 'Data validade', type: 'date' },
      ],
    },
  ],
  normalizeRecord: (record: CrudRecord) => ({
    ...record,
    id_produto_lookup: toLookupOption(record.produto, ['nome'], record.id_produto),
    id_filial_lookup: toLookupOption(record.filial, ['nome_fantasia', 'nome'], record.id_filial),
    id_tabela_preco_lookup: toLookupOption(record.tabela_preco, ['nome'], record.id_tabela_preco),
    id_canal_distribuicao_lookup: toLookupOption(record.canal_distribuicao, ['nome'], record.id_canal_distribuicao_cliente),
    pedido_minimo: formatPriceStockDecimal(record.pedido_minimo, 2),
    pedido_maximo: formatPriceStockDecimal(record.pedido_maximo, 2),
    preco: formatPriceStockDecimal(record.preco, 2),
    preco_promocao: formatPriceStockDecimal(record.preco_promocao, 2),
    preco_custo: formatPriceStockDecimal(record.preco_custo, 2),
    preco_fidelidade: formatPriceStockDecimal(record.preco_fidelidade, 2),
    preco_app: formatPriceStockDecimal(record.preco_app, 2),
    preco_minimo: formatPriceStockDecimal(record.preco_minimo, 2),
    preco_venda: formatPriceStockDecimal(record.preco_venda, 2),
    desconto: formatPriceStockDecimal(record.desconto, 2),
    acrescimo: formatPriceStockDecimal(record.acrescimo, 2),
    data_inicio_promocao: formatApiDateToInput(record.data_inicio_promocao),
    data_fim_promocao: formatApiDateToInput(record.data_fim_promocao),
    data_inicio_fidelidade: formatApiDateToInput(record.data_inicio_fidelidade),
    data_fim_fidelidade: formatApiDateToInput(record.data_fim_fidelidade),
    data_inicio_app: formatApiDateToInput(record.data_inicio_app),
    data_fim_app: formatApiDateToInput(record.data_fim_app),
    data_validade: formatApiDateToInput(record.data_validade),
  }),
  beforeSave: (record: CrudRecord) => ({
    ...record,
    id_produto: String((record.id_produto_lookup as { id?: unknown } | null)?.id || record.id_produto || '').trim() || null,
    id_filial: String((record.id_filial_lookup as { id?: unknown } | null)?.id || record.id_filial || '').trim() || null,
    id_tabela_preco: String((record.id_tabela_preco_lookup as { id?: unknown } | null)?.id || record.id_tabela_preco || '').trim() || null,
    id_canal_distribuicao_cliente: String((record.id_canal_distribuicao_lookup as { id?: unknown } | null)?.id || record.id_canal_distribuicao_cliente || '').trim() || null,
    tipo_preco: String(record.tipo_preco || '').trim() || null,
    estoque_minimo: parseInteger(record.estoque_minimo),
    estoque_disponivel: parseInteger(record.estoque_disponivel),
    estoque_reservado: parseInteger(record.estoque_reservado),
    prazo_entrega: parseInteger(record.prazo_entrega),
    pedido_minimo: parsePriceStockDecimal(record.pedido_minimo),
    pedido_maximo: parsePriceStockDecimal(record.pedido_maximo),
    preco: parsePriceStockDecimal(record.preco),
    preco_promocao: parsePriceStockDecimal(record.preco_promocao),
    preco_custo: parsePriceStockDecimal(record.preco_custo),
    preco_fidelidade: parsePriceStockDecimal(record.preco_fidelidade),
    preco_app: parsePriceStockDecimal(record.preco_app),
    preco_minimo: parsePriceStockDecimal(record.preco_minimo),
    preco_venda: parsePriceStockDecimal(record.preco_venda),
    desconto: parsePriceStockDecimal(record.desconto),
    acrescimo: parsePriceStockDecimal(record.acrescimo),
    data_inicio_promocao: formatInputDateToApiStart(record.data_inicio_promocao),
    data_fim_promocao: formatInputDateToApiEnd(record.data_fim_promocao),
    data_inicio_fidelidade: formatInputDateToApiStart(record.data_inicio_fidelidade),
    data_fim_fidelidade: formatInputDateToApiEnd(record.data_fim_fidelidade),
    data_inicio_app: formatInputDateToApiStart(record.data_inicio_app),
    data_fim_app: formatInputDateToApiEnd(record.data_fim_app),
    data_validade: formatInputDateToApiEnd(record.data_validade),
    id_sync: undefined,
    metadata: undefined,
    id_produto_lookup: undefined,
    id_filial_lookup: undefined,
    id_tabela_preco_lookup: undefined,
    id_canal_distribuicao_lookup: undefined,
  }),
}
