'use client'

import { loadCrudLookupOptions } from '@/src/components/crud-base/crud-client'
import type { CrudModuleConfig, CrudRecord } from '@/src/components/crud-base/types'
import { BRAZILIAN_STATES } from '@/src/lib/brazil'
import { toLookupOption } from '@/src/lib/lookup-options'
import { formatPriceStockDecimal, parsePriceStockDecimal } from '@/src/features/precos-estoques/services/precos-estoques-shared'

export const TRIBUTOS_CONFIG: CrudModuleConfig = {
  key: 'tributos',
  resource: 'tributos',
  routeBase: '/tributos',
  featureKey: 'tributos',
  listTitleKey: 'priceStock.taxes.title',
  listTitle: 'Tributos',
  listDescriptionKey: 'priceStock.taxes.listDescription',
  listDescription: 'Listagem com produto, tabela de preço, UF e status ativo.',
  formTitleKey: 'priceStock.taxes.formTitle',
  formTitle: 'Tributo',
  breadcrumbSectionKey: 'routes.precosEstoques',
  breadcrumbSection: 'Preços e Estoques',
  breadcrumbModuleKey: 'routes.tributos',
  breadcrumbModule: 'Tributos',
  listEmbed: 'produto,tabela_preco',
  formEmbed: 'produto,tabela_preco',
  defaultFilters: {
    page: 1,
    perPage: 15,
    orderBy: 'id',
    sort: 'desc',
    id: '',
    id_produto: '',
    id_tabela_preco: '',
    uf: '',
    ativo: '',
  },
  columns: [
    { id: 'id', labelKey: 'simpleCrud.fields.id', label: 'ID', sortKey: 'id', thClassName: 'w-[180px]', filter: { kind: 'text', key: 'id' } },
    {
      id: 'id_produto',
      labelKey: 'priceStock.taxes.fields.product',
      label: 'Produto',
      sortKey: 'id_produto',
      tdClassName: 'font-semibold text-slate-950',
      render: (record) => String((record.produto as { nome?: unknown } | null)?.nome || record.id_produto || '-'),
      filter: {
        kind: 'lookup',
        key: 'id_produto',
        loadOptions: (query, page, perPage) => loadCrudLookupOptions('produtos', query, page, perPage).then((items) => items.map((item) => ({ id: item.value, label: item.label }))),
      },
    },
    {
      id: 'id_tabela_preco',
      labelKey: 'priceStock.taxes.fields.priceTable',
      label: 'Tabela de preço',
      sortKey: 'id_tabela_preco',
      render: (record) => String((record.tabela_preco as { nome?: unknown } | null)?.nome || record.id_tabela_preco || '-'),
      filter: {
        kind: 'lookup',
        key: 'id_tabela_preco',
        loadOptions: (query, page, perPage) => loadCrudLookupOptions('tabelas_preco', query, page, perPage).then((items) => items.map((item) => ({ id: item.value, label: item.label }))),
      },
    },
    { id: 'uf', labelKey: 'priceStock.taxes.fields.state', label: 'UF', sortKey: 'uf', thClassName: 'w-[100px]', filter: { kind: 'select', key: 'uf', options: BRAZILIAN_STATES.map((value) => ({ value, label: value })) } },
    { id: 'ativo', labelKey: 'simpleCrud.fields.active', label: 'Ativo', sortKey: 'ativo', thClassName: 'w-[100px]', valueKey: 'ativo', filter: { kind: 'select', key: 'ativo', options: [{ value: '1', label: 'Sim' }, { value: '0', label: 'Não' }] } },
  ],
  mobileTitle: (record) => String((record.produto as { nome?: unknown } | null)?.nome || '-'),
  mobileSubtitle: (record) => String((record.tabela_preco as { nome?: unknown } | null)?.nome || '-'),
  mobileMeta: (record) => `UF: ${String(record.uf || '-')}`,
  sections: [
    {
      id: 'general',
      titleKey: 'priceStock.sections.general',
      title: 'Dados gerais',
      layout: 'rows',
      fields: [
        { key: 'ativo', labelKey: 'simpleCrud.fields.active', label: 'Ativo', type: 'toggle' },
        { key: 'fonte_st', labelKey: 'priceStock.taxes.fields.sourceSt', label: 'Fonte ST', type: 'toggle' },
        { key: 'id_filial', labelKey: 'priceStock.taxes.fields.branch', label: 'Filial', type: 'lookup', optionsResource: 'filiais', lookupStateKey: 'id_filial_lookup' },
        { key: 'id_produto', labelKey: 'priceStock.taxes.fields.product', label: 'Produto', type: 'lookup', optionsResource: 'produtos', lookupStateKey: 'id_produto_lookup' },
        { key: 'id_tabela_preco', labelKey: 'priceStock.taxes.fields.priceTable', label: 'Tabela de preço', type: 'lookup', optionsResource: 'tabelas_preco', lookupStateKey: 'id_tabela_preco_lookup' },
        { key: 'uf', labelKey: 'priceStock.taxes.fields.state', label: 'UF', type: 'select', options: BRAZILIAN_STATES.map((value) => ({ value, label: value })) },
        {
          key: 'tipo_calculo_fecoep',
          labelKey: 'priceStock.taxes.fields.fecoepCalculationType',
          label: 'Tipo cálculo FECOEP',
          type: 'select',
          options: [
            { value: '', labelKey: 'common.select', label: 'Selecione' },
            { value: 'base_reduzida', labelKey: 'priceStock.taxes.options.fecoepReducedBase', label: 'Base reduzida' },
          ],
        },
      ],
    },
    {
      id: 'rates',
      titleKey: 'priceStock.taxes.sections.rates',
      title: 'Alíquotas e bases',
      layout: 'rows',
      fields: [
        { key: 'iva', labelKey: 'priceStock.taxes.fields.iva', label: 'IVA', type: 'text', mask: 'decimal', suffixText: '%' },
        { key: 'iva_fonte_st', labelKey: 'priceStock.taxes.fields.ivaSourceSt', label: 'IVA fonte ST', type: 'text', mask: 'decimal', suffixText: '%' },
        { key: 'icms_interno', labelKey: 'priceStock.taxes.fields.icmsInternal', label: 'ICMS interno', type: 'text', mask: 'decimal', suffixText: '%' },
        { key: 'icms_interno_fonte_st', labelKey: 'priceStock.taxes.fields.icmsInternalSourceSt', label: 'ICMS interno fonte ST', type: 'text', mask: 'decimal', suffixText: '%' },
        { key: 'icms_externo', labelKey: 'priceStock.taxes.fields.icmsExternal', label: 'ICMS externo', type: 'text', mask: 'decimal', suffixText: '%' },
        { key: 'icms_externo_fonte_st', labelKey: 'priceStock.taxes.fields.icmsExternalSourceSt', label: 'ICMS externo fonte ST', type: 'text', mask: 'decimal', suffixText: '%' },
        { key: 'reducao_base', labelKey: 'priceStock.taxes.fields.baseReduction', label: 'Redução base', type: 'text', mask: 'decimal', suffixText: '%' },
        { key: 'reducao_base_fonte_st', labelKey: 'priceStock.taxes.fields.baseReductionSourceSt', label: 'Redução base fonte ST', type: 'text', mask: 'decimal', suffixText: '%' },
        { key: 'valor_pauta', labelKey: 'priceStock.taxes.fields.referenceValue', label: 'Valor pauta', type: 'text', mask: 'currency', prefixText: 'R$' },
        { key: 'valor_pauta_fonte_st', labelKey: 'priceStock.taxes.fields.referenceValueSourceSt', label: 'Valor pauta fonte ST', type: 'text', mask: 'currency', prefixText: 'R$' },
        { key: 'isencao_pis', labelKey: 'priceStock.taxes.fields.pisExemption', label: 'Isenção PIS', type: 'text', mask: 'decimal', suffixText: '%' },
        { key: 'isencao_cofins', labelKey: 'priceStock.taxes.fields.cofinsExemption', label: 'Isenção COFINS', type: 'text', mask: 'decimal', suffixText: '%' },
        { key: 'fecoep', labelKey: 'priceStock.taxes.fields.fecoep', label: 'FECOEP', type: 'text', mask: 'decimal', suffixText: '%' },
      ],
    },
  ],
  normalizeRecord: (record: CrudRecord) => ({
    ...record,
    id_filial_lookup: toLookupOption(record.filial, ['nome_fantasia', 'nome'], record.id_filial),
    id_produto_lookup: toLookupOption(record.produto, ['nome'], record.id_produto),
    id_tabela_preco_lookup: toLookupOption(record.tabela_preco, ['nome'], record.id_tabela_preco),
    iva: formatPriceStockDecimal(record.iva, 4),
    iva_fonte_st: formatPriceStockDecimal(record.iva_fonte_st, 4),
    icms_interno: formatPriceStockDecimal(record.icms_interno, 4),
    icms_interno_fonte_st: formatPriceStockDecimal(record.icms_interno_fonte_st, 4),
    icms_externo: formatPriceStockDecimal(record.icms_externo, 4),
    icms_externo_fonte_st: formatPriceStockDecimal(record.icms_externo_fonte_st, 4),
    reducao_base: formatPriceStockDecimal(record.reducao_base, 4),
    reducao_base_fonte_st: formatPriceStockDecimal(record.reducao_base_fonte_st, 4),
    valor_pauta: formatPriceStockDecimal(record.valor_pauta, 2),
    valor_pauta_fonte_st: formatPriceStockDecimal(record.valor_pauta_fonte_st, 2),
    isencao_pis: formatPriceStockDecimal(record.isencao_pis, 4),
    isencao_cofins: formatPriceStockDecimal(record.isencao_cofins, 4),
    fecoep: formatPriceStockDecimal(record.fecoep, 4),
  }),
  beforeSave: (record: CrudRecord) => ({
    ...record,
    id_filial: String((record.id_filial_lookup as { id?: unknown } | null)?.id || record.id_filial || '').trim() || null,
    id_produto: String((record.id_produto_lookup as { id?: unknown } | null)?.id || record.id_produto || '').trim() || null,
    id_tabela_preco: String((record.id_tabela_preco_lookup as { id?: unknown } | null)?.id || record.id_tabela_preco || '').trim() || null,
    iva: parsePriceStockDecimal(record.iva),
    iva_fonte_st: parsePriceStockDecimal(record.iva_fonte_st),
    icms_interno: parsePriceStockDecimal(record.icms_interno),
    icms_interno_fonte_st: parsePriceStockDecimal(record.icms_interno_fonte_st),
    icms_externo: parsePriceStockDecimal(record.icms_externo),
    icms_externo_fonte_st: parsePriceStockDecimal(record.icms_externo_fonte_st),
    reducao_base: parsePriceStockDecimal(record.reducao_base),
    reducao_base_fonte_st: parsePriceStockDecimal(record.reducao_base_fonte_st),
    valor_pauta: parsePriceStockDecimal(record.valor_pauta),
    valor_pauta_fonte_st: parsePriceStockDecimal(record.valor_pauta_fonte_st),
    isencao_pis: parsePriceStockDecimal(record.isencao_pis),
    isencao_cofins: parsePriceStockDecimal(record.isencao_cofins),
    fecoep: parsePriceStockDecimal(record.fecoep),
    id_sync: undefined,
    metadata: undefined,
    id_filial_lookup: undefined,
    id_produto_lookup: undefined,
    id_tabela_preco_lookup: undefined,
  }),
}
