'use client'

import type { CrudFieldOption, CrudModuleConfig } from '@/src/components/crud-base/types'
import { normalizeEmailTemplateRecord } from '@/src/features/emails-templates/services/emails-templates-normalizer'

const EMAIL_TEMPLATE_TYPE_OPTIONS: CrudFieldOption[] = [
  { value: '', labelKey: 'common.select', label: 'Selecione' },
  { value: 'cadastro_cliente', labelKey: 'maintenance.emailTemplates.types.cadastro_cliente', label: 'Cadastro de Cliente' },
  { value: 'solicitacao_cadastro', labelKey: 'maintenance.emailTemplates.types.solicitacao_cadastro', label: 'Solicitação de Cadastro' },
  { value: 'cliente_aprovado', labelKey: 'maintenance.emailTemplates.types.cliente_aprovado', label: 'Cliente Aprovado' },
  { value: 'cliente_reprovado', labelKey: 'maintenance.emailTemplates.types.cliente_reprovado', label: 'Cliente Reprovado' },
  { value: 'senha_ativacao', labelKey: 'maintenance.emailTemplates.types.senha_ativacao', label: 'Senha de Ativação' },
  { value: 'nova_senha', labelKey: 'maintenance.emailTemplates.types.nova_senha', label: 'Nova Senha' },
  { value: 'pedido_recebido', labelKey: 'maintenance.emailTemplates.types.pedido_recebido', label: 'Pedido Recebido' },
  { value: 'pedido_aprovado', labelKey: 'maintenance.emailTemplates.types.pedido_aprovado', label: 'Pedido Aprovado' },
  { value: 'pedido_reprovado', labelKey: 'maintenance.emailTemplates.types.pedido_reprovado', label: 'Pedido Reprovado' },
  { value: 'pedido_cancelado', labelKey: 'maintenance.emailTemplates.types.pedido_cancelado', label: 'Pedido Cancelado' },
  { value: 'pedido_faturado', labelKey: 'maintenance.emailTemplates.types.pedido_faturado', label: 'Pedido Faturado' },
  { value: 'pedido_em_transporte', labelKey: 'maintenance.emailTemplates.types.pedido_em_transporte', label: 'Pedido em Transporte' },
  { value: 'pedido_entregue', labelKey: 'maintenance.emailTemplates.types.pedido_entregue', label: 'Pedido Entregue' },
  { value: 'pedido_coletado', labelKey: 'maintenance.emailTemplates.types.pedido_coletado', label: 'Pedido Coletado' },
  { value: 'pedido_pronto_retirada', labelKey: 'maintenance.emailTemplates.types.pedido_pronto_retirada', label: 'Pedido Pronto para Retirada' },
  { value: 'orcamento_recebido', labelKey: 'maintenance.emailTemplates.types.orcamento_recebido', label: 'Orçamento Recebido' },
  { value: 'pedido_carrinho', labelKey: 'maintenance.emailTemplates.types.pedido_carrinho', label: 'Pedido Carrinho' },
]

export const EMAILS_TEMPLATES_CONFIG: CrudModuleConfig = {
  key: 'emailsTemplates',
  resource: 'emails_templates',
  routeBase: '/templates-de-emails',
  featureKey: 'templatesEmails',
  listTitleKey: 'maintenance.emailTemplates.title',
  listTitle: 'Templates de E-mails',
  listDescriptionKey: 'maintenance.emailTemplates.listDescription',
  listDescription: 'Gerencie templates com regras de envio por perfil e tipo de evento.',
  formTitleKey: 'maintenance.emailTemplates.formTitle',
  formTitle: 'Template de E-mail',
  breadcrumbSectionKey: 'routes.manutencao',
  breadcrumbSection: 'Manutenção',
  breadcrumbModuleKey: 'maintenance.emailTemplates.title',
  breadcrumbModule: 'Templates de E-mails',
  defaultFilters: {
    page: 1,
    perPage: 15,
    orderBy: 'id',
    sort: 'desc',
    id: '',
    codigo: '',
    'titulo::like': '',
    ativo: '',
  },
  columns: [
    { id: 'id', labelKey: 'simpleCrud.fields.id', label: 'ID', sortKey: 'id', thClassName: 'w-[110px]', filter: { kind: 'text', key: 'id' } },
    { id: 'codigo', labelKey: 'simpleCrud.fields.code', label: 'Código', sortKey: 'codigo', thClassName: 'w-[150px]', filter: { kind: 'text', key: 'codigo' } },
    { id: 'titulo', labelKey: 'simpleCrud.fields.title', label: 'Título', sortKey: 'titulo', tdClassName: 'font-semibold text-slate-950', filter: { kind: 'text', key: 'titulo::like' } },
    {
      id: 'ativo',
      labelKey: 'simpleCrud.fields.active',
      label: 'Ativo',
      sortKey: 'ativo',
      thClassName: 'w-[110px]',
      valueKey: 'ativo',
      filter: {
        kind: 'select',
        key: 'ativo',
        options: [
          { value: '1', labelKey: 'common.yes', label: 'Sim' },
          { value: '0', labelKey: 'common.no', label: 'Não' },
        ],
      },
    },
  ],
  mobileTitle: (record) => String(record.titulo || '-'),
  mobileSubtitle: (record) => String(record.codigo || '-'),
  mobileMeta: (record) => `ID: ${record.id}`,
  sections: [
    {
      id: 'main',
      titleKey: 'simpleCrud.sections.main',
      title: 'Dados principais',
      layout: 'rows',
      fields: [
        { key: 'ativo', labelKey: 'simpleCrud.fields.active', label: 'Ativo', type: 'toggle' },
        { key: 'codigo', labelKey: 'simpleCrud.fields.code', label: 'Código', type: 'text', maxLength: 32 },
        { key: 'titulo', labelKey: 'simpleCrud.fields.title', label: 'Título', type: 'text', required: true, maxLength: 128 },
        { key: 'tipo', labelKey: 'maintenance.emailTemplates.fields.type', label: 'Tipo', type: 'select', options: EMAIL_TEMPLATE_TYPE_OPTIONS },
        { key: 'tempo_envio', labelKey: 'maintenance.emailTemplates.fields.sendDelay', label: 'Tempo de envio (min)', type: 'number' },
        { key: 'enviar_para', labelKey: 'maintenance.emailTemplates.fields.sendTo', label: 'Enviar para', type: 'text', helperTextKey: 'maintenance.emailTemplates.sendToHint', helperText: 'Lista de e-mails separada por vírgula.' },
      ],
    },
    {
      id: 'recipients',
      titleKey: 'maintenance.emailTemplates.sections.recipients',
      title: 'Regras de destinatários',
      layout: 'rows',
      fields: [
        { key: 'envia_empresa', labelKey: 'maintenance.emailTemplates.fields.envia_empresa', label: 'Envia empresa', type: 'toggle' },
        { key: 'envia_filial', labelKey: 'maintenance.emailTemplates.fields.envia_filial', label: 'Envia filial', type: 'toggle' },
        { key: 'envia_filial_estoque', labelKey: 'maintenance.emailTemplates.fields.envia_filial_estoque', label: 'Envia filial estoque', type: 'toggle' },
        { key: 'envia_filial_retira', labelKey: 'maintenance.emailTemplates.fields.envia_filial_retira', label: 'Envia filial retira', type: 'toggle' },
        { key: 'envia_usuario', labelKey: 'maintenance.emailTemplates.fields.envia_usuario', label: 'Envia usuário', type: 'toggle' },
        { key: 'envia_cliente', labelKey: 'maintenance.emailTemplates.fields.envia_cliente', label: 'Envia cliente', type: 'toggle' },
        { key: 'envia_contato', labelKey: 'maintenance.emailTemplates.fields.envia_contato', label: 'Envia contato', type: 'toggle' },
        { key: 'envia_vendedor', labelKey: 'maintenance.emailTemplates.fields.envia_vendedor', label: 'Envia vendedor', type: 'toggle' },
      ],
    },
  ],
  normalizeRecord: normalizeEmailTemplateRecord,
  beforeSave: normalizeEmailTemplateRecord,
}
