import type { ClientFormRecord } from '@/src/features/clientes/types/clientes'

export function createEmptyClientForm(): ClientFormRecord {
  return {
    id: '',
    idClasse: '',
    ativo: true,
    bloqueado: false,
    bloqueadoPlataforma: false,
    liberado: true,
    contribuinte: false,
    codigo: '',
    codigoAtivacao: '',
    tipo: 'PJ',
    cpf: '',
    cnpj: '',
    nome: '',
    razaoSocial: '',
    nomeFantasia: '',
    sexo: 'M',
    rg: '',
    dataNascimento: '',
    inscricaoEstadual: '',
    isentoIe: false,
    limiteCredito: '',
    limiteDisponivel: '',
    tipoCliente: '',
    ramoAtividade: '',
    pessoaContato: '',
    email: '',
    telefone1: '',
    telefone2: '',
    celular: '',
    cep: '',
    endereco: '',
    numero: '',
    complemento: '',
    bairro: '',
    cidade: '',
    uf: '',
    observacoesBloqueio: '',
    observacoesBloqueioPlataforma: '',
    classificacao: {
      rede: null,
      segmento: null,
      canalDistribuicao: null,
      filial: null,
      vendedor: null,
      tabelaPreco: null,
      formaPagamento: null,
      condicaoPagamento: null,
      formaPagamentoPadrao: null,
      condicaoPagamentoPadrao: null,
    },
    filiais: [],
    vendedores: [],
    formasPagamento: [],
    condicoesPagamento: [],
    formularios: [],
  }
}

export function createCompositeRelationId(a: string, b?: string) {
  return b ? `${a}:${b}` : a
}
