'use client'

import type { CrudModuleConfig, CrudRecord } from '@/src/components/crud-base/types'
import { formatCpfCnpj, formatDate } from '@/src/lib/formatters'
import { mapSupervisorDetail, toSupervisorPayload } from '@/src/features/supervisores/services/supervisores-form'

export const SUPERVISORES_CONFIG: CrudModuleConfig = {
  key: 'supervisores',
  resource: 'supervisores',
  routeBase: '/supervisores',
  featureKey: 'supervisores',
  listTitleKey: 'people.supervisores.title',
  listTitle: 'Supervisores',
  listDescriptionKey: 'people.supervisores.listDescription',
  listDescription: 'Listagem fiel ao legado com filtros centrais, status e ordenação server-side.',
  formTitleKey: 'people.supervisores.formTitle',
  formTitle: 'Supervisor',
  breadcrumbSectionKey: 'routes.people',
  breadcrumbSection: 'Pessoas',
  breadcrumbModuleKey: 'people.supervisores.title',
  breadcrumbModule: 'Supervisores',
  defaultFilters: {
    page: 1,
    perPage: 15,
    orderBy: 'nome',
    sort: 'asc',
    id: '',
    codigo: '',
    cnpj_cpf: '',
    'nome::like': '',
    bloqueado: '',
    ativo: '',
  },
  columns: [
    { id: 'id', labelKey: 'simpleCrud.fields.id', label: 'ID', sortKey: 'id', thClassName: 'w-[180px]', filter: { kind: 'text', key: 'id' } },
    { id: 'codigo', labelKey: 'simpleCrud.fields.code', label: 'Código', sortKey: 'codigo', thClassName: 'w-[130px]', filter: { kind: 'text', key: 'codigo' } },
    {
      id: 'cnpj_cpf',
      labelKey: 'people.supervisores.fields.document',
      label: 'CPF/CNPJ',
      sortKey: 'cnpj_cpf',
      thClassName: 'w-[160px]',
      render: (record) => formatCpfCnpj(record.cnpj_cpf),
      filter: { kind: 'text', key: 'cnpj_cpf', labelKey: 'people.supervisores.fields.document', label: 'CPF/CNPJ' },
    },
    {
      id: 'nome',
      labelKey: 'simpleCrud.fields.name',
      label: 'Nome',
      sortKey: 'nome',
      tdClassName: 'font-semibold text-slate-950',
      filter: { kind: 'text', key: 'nome::like' },
    },
    {
      id: 'bloqueado',
      labelKey: 'people.supervisores.fields.blocked',
      label: 'Bloqueado',
      sortKey: 'bloqueado',
      thClassName: 'w-[110px]',
      valueKey: 'bloqueado',
      filter: {
        kind: 'select',
        key: 'bloqueado',
        labelKey: 'people.supervisores.fields.blocked',
        label: 'Bloqueado',
        options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }],
      },
    },
    {
      id: 'ativo',
      labelKey: 'simpleCrud.fields.active',
      label: 'Ativo',
      sortKey: 'ativo',
      thClassName: 'w-[100px]',
      valueKey: 'ativo',
      filter: { kind: 'select', key: 'ativo', options: [{ value: '1', label: 'Yes' }, { value: '0', label: 'No' }] },
    },
  ],
  mobileTitle: (record) => String(record.nome || '-'),
  mobileSubtitle: (record) => formatCpfCnpj(record.cnpj_cpf),
  mobileMeta: (record) => `ID: ${String(record.id || '-')}`,
  details: [
    {
      key: 'codigo_ativacao',
      labelKey: 'people.supervisores.fields.activationCode',
      label: 'Código de ativação',
      render: (record) => String(record.codigo_ativacao || '-'),
    },
    { key: 'email', labelKey: 'simpleCrud.fields.email', label: 'E-mail', render: (record) => String(record.email || '-') },
    {
      key: 'updated_at',
      labelKey: 'common.updatedAt',
      label: 'Atualizado em',
      render: (record) => record.updated_at ? formatDate(String(record.updated_at)) : '-',
    },
  ],
  sections: [
    {
      id: 'general',
      titleKey: 'simpleCrud.sections.main',
      title: 'Dados principais',
      layout: 'rows',
      fields: [
        { key: 'ativo', labelKey: 'simpleCrud.fields.active', label: 'Ativo', type: 'toggle' },
        { key: 'bloqueado', labelKey: 'people.supervisores.fields.blocked', label: 'Bloqueado', type: 'toggle' },
        { key: 'codigo', labelKey: 'simpleCrud.fields.code', label: 'Código', type: 'text' },
        { key: 'codigo_ativacao', labelKey: 'people.supervisores.fields.activationCode', label: 'Código de ativação', type: 'text' },
        {
          key: 'tipo',
          labelKey: 'people.supervisores.fields.type',
          label: 'Tipo',
          type: 'select',
          options: [
            { value: 'PF', labelKey: 'people.personType.pf', label: 'Pessoa Física' },
            { value: 'PJ', labelKey: 'people.personType.pj', label: 'Pessoa Jurídica' },
          ],
        },
        {
          key: 'cpf',
          labelKey: 'people.supervisores.fields.cpf',
          label: 'CPF',
          type: 'text',
          mask: 'cpf',
          required: true,
          hidden: ({ form }) => String(form.tipo || 'PF') !== 'PF',
        },
        {
          key: 'nome',
          labelKey: 'simpleCrud.fields.name',
          label: 'Nome',
          type: 'text',
          required: true,
          hidden: ({ form }) => String(form.tipo || 'PF') !== 'PF',
        },
        {
          key: 'cnpj',
          labelKey: 'people.supervisores.fields.cnpj',
          label: 'CNPJ',
          type: 'text',
          mask: 'cnpj',
          required: true,
          hidden: ({ form }) => String(form.tipo || 'PF') !== 'PJ',
        },
        {
          key: 'nome_fantasia',
          labelKey: 'people.supervisores.fields.tradeName',
          label: 'Nome fantasia',
          type: 'text',
          required: true,
          hidden: ({ form }) => String(form.tipo || 'PF') !== 'PJ',
        },
        {
          key: 'id_filial',
          labelKey: 'people.supervisores.fields.branch',
          label: 'Filial',
          type: 'lookup',
          optionsResource: 'filiais',
          lookupStateKey: 'id_filial_lookup',
        },
        {
          key: 'id_canal_distribuicao',
          labelKey: 'people.supervisores.fields.distributionChannel',
          label: 'Canal de distribuição',
          type: 'lookup',
          optionsResource: 'canais_distribuicao',
          lookupStateKey: 'id_canal_distribuicao_lookup',
        },
        { key: 'email', labelKey: 'simpleCrud.fields.email', label: 'E-mail', type: 'email' },
        { key: 'telefone', labelKey: 'people.supervisores.fields.phone', label: 'Telefone', type: 'text', mask: 'phone' },
        { key: 'celular', labelKey: 'people.supervisores.fields.mobile', label: 'Celular', type: 'text', mask: 'mobile' },
      ],
    },
  ],
  formEmbed: 'filial,canal_distribuicao',
  normalizeRecord: (record: CrudRecord) => {
    const mapped = mapSupervisorDetail(record)
    return {
      ...mapped,
      id_filial: mapped.id_filial?.id || '',
      id_filial_lookup: mapped.id_filial,
      id_canal_distribuicao: mapped.id_canal_distribuicao?.id || '',
      id_canal_distribuicao_lookup: mapped.id_canal_distribuicao,
    }
  },
  beforeSave: (record: CrudRecord) => toSupervisorPayload({
    id: String(record.id || ''),
    ativo: record.ativo === true,
    bloqueado: record.bloqueado === true,
    codigo: String(record.codigo || ''),
    codigo_ativacao: String(record.codigo_ativacao || ''),
    tipo: String(record.tipo || 'PF') === 'PJ' ? 'PJ' : 'PF',
    cpf: String(record.cpf || ''),
    cnpj: String(record.cnpj || ''),
    nome: String(record.nome || ''),
    nome_fantasia: String(record.nome_fantasia || ''),
    id_filial: record.id_filial_lookup && typeof record.id_filial_lookup === 'object'
      ? record.id_filial_lookup as { id: string; label: string }
      : null,
    id_canal_distribuicao: record.id_canal_distribuicao_lookup && typeof record.id_canal_distribuicao_lookup === 'object'
      ? record.id_canal_distribuicao_lookup as { id: string; label: string }
      : null,
    email: String(record.email || ''),
    telefone: String(record.telefone || ''),
    celular: String(record.celular || ''),
  }),
}
